src_path: http://100.114.33.35:5280/api/config/client/246cb982-8bb0-417f-8440-1202c2451d24

jobs:
 - name : job1
   event : vdfv
   cmd : ping -c 5 localhost && cat {{task_id}}.json && rm {{task_id}}.json
 - name : job2
   event : generate_html_to_image
   cmd : ping -c 20 localhost