credential:
  project_id: 7bd0c868-87a0-4c90-8d27-559677763bb6
  secret_key: xxx-xxx-xxx
end_point: http://134.209.109.179:5280/api/worker/config
jobs:
  - name: Validate Doc And Style
    event: validate_doc_and_style
    cmd: cat {{task_id}}.json && rm {{task_id}}.json
  - name: Send email
    event: send_email
    cmd: cat {{task_id}}.json && rm {{task_id}}.json
  - name: Validate Logo
    event: validate_logo
    cmd: cat {{task_id}}.json && rm {{task_id}}.json